<div class="arroundContact">
  <div class="container">
      <h1>Formulaire de contact</h1>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
      <div class="row">
        <div class="col-lg-3">
          <input id="mail" type="text" name="mail" placeholder="email" />
          <input id="name" type="text" name="name" placeholder="name" />
          <input id="adress" type="text" name="adress" placeholder="adress" />
          <input id="city" type="text" name="city" placeholder="city" />
          <input id="cp" type="text" name="cp" placeholder="cp" />
          <input id="message" type="text" name="message" placeholder="your message here" />
          <button id="contact_submit">SEND</button>
          <div class="testing"></div>
        </div>
        <div class="col-lg-9">
          <div class="result-form">
            
          </div>
        </div>
      </div>

  </div>
</div>
